# -*- coding: utf-8 -*-
"""genel_hukuk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD6SmAzFSEOYc66lIxnJomHb2Ed2HRyE
"""

# --- 1. AYARLAR VE KÜTÜPHANELER ---
!pip install groq datasets sentence-transformers -q

import os
import re
import torch
from google.colab import userdata
from groq import Groq
from datasets import load_dataset
from sentence_transformers import SentenceTransformer, util

# --- MODELLER BURADA TANIMLI (KOLAY ERİŞİM) ---
EMBEDDING_MODEL_NAME = 'sentence-transformers/all-MiniLM-L6-v2' # Arama Modeli
LLM_MODEL_NAME = "llama-3.3-70b-versatile"                       # Cevap Modeli - GÜNCELLENDİ

# API Key Kontrolü
try:
    api_key = userdata.get('GROQ_API_KEY')
except:
    api_key = os.environ.get("GROQ_API_KEY")

if not api_key:
    print("⚠️ HATA: Groq API Key bulunamadı! Lütfen sol menüdeki 'Anahtar' (Secrets) kısmına ekleyin.")
else:
    client = Groq(api_key=api_key)
    print("✅ API Bağlantısı Hazır")

# --- 2. RAG MOTORU (ARAMA SİSTEMİ) ---
class SemanticRAG:
    def __init__(self):
        self.vector_store = []
        self.contents = []
        print(f"🧠 Arama Modeli Yükleniyor: {EMBEDDING_MODEL_NAME}...")
        try:
            self.model = SentenceTransformer(EMBEDDING_MODEL_NAME)
            print("✅ Arama Modeli Hazır!")
        except Exception as e:
            print(f"❌ Model Yükleme Hatası: {e}")

    def ingest(self, text_list):
        if not text_list: return
        print(f"🔄 {len(text_list)} veri işleniyor...")
        self.vector_store = self.model.encode(text_list, convert_to_tensor=True)
        self.contents = text_list
        print("✅ Veriler hafızaya alındı.")

    def retrieve(self, query, top_k=3):
        query_vec = self.model.encode(query, convert_to_tensor=True)
        cosine_scores = util.cos_sim(query_vec, self.vector_store)[0]
        top_results = torch.topk(cosine_scores, k=min(top_k, len(self.contents)))

        results = []
        for score, idx in zip(top_results[0], top_results[1]):
            if score > 0.35:
                results.append(self.contents[idx])

        return "\n---\n".join(results) if results else "Veritabanında bilgi yok."

# --- 3. DATASET YÜKLEME ---
rag_engine = SemanticRAG()

print("📥 Dataset indiriliyor...")
try:
    ds = load_dataset("akerem1427/Hukukv4", split="train")
    # Hızlı test için ilk 2000 veriyi alıyoruz
    ds_subset = ds.select(range(min(len(ds), 2000)))

    text_data = []
    for row in ds_subset:
        combined = ""
        if 'instruction' in row and 'output' in row:
            combined = f"SORU: {row['instruction']}\nCEVAP: {row['output']}"
        elif 'text' in row:
            combined = row['text']

        if len(combined) > 20:
            text_data.append(combined)

    rag_engine.ingest(text_data)
except Exception as e:
    print(f"❌ Dataset Hatası: {e}")

# --- 4. ARAÇLAR VE AJAN ---
def kanun_ara(query: str) -> str:
    return rag_engine.retrieve(query)

def calculator(expression: str) -> str:
    try: return str(eval(expression, {"__builtins__": None}, {}))
    except: return "Hata"

tools = [kanun_ara, calculator]
known_actions = {t.__name__: t for t in tools}

system_prompt = f"""
Sen Türk Hukuk Asistanısın.
Kurallar:
1. 'kanun_ara' ile veritabanından bilgi bul.
2. Hesaplama için 'calculator' kullan.
3. Sadece bulduğun kanuna göre cevap ver.
Araçlar: kanun_ara, calculator
"""

class Agent:
    def __init__(self):
        self.messages = [{"role": "system", "content": system_prompt}]

    def execute(self, message):
        self.messages.append({"role": "user", "content": message})
        try:
            result = client.chat.completions.create(
                model=LLM_MODEL_NAME, # <--- Model burada kullanılıyor
                messages=self.messages,
                temperature=0,
                stop=["PAUSE", "Observation:"]
            )
            response = result.choices[0].message.content
            self.messages.append({"role": "assistant", "content": response})
            return response
        except Exception as e:
            return f"API Hatası: {e}"

# --- 5. ÇALIŞTIRMA ---
action_re = re.compile(r'^Action: (\w+): (.*)$')

def query(question):
    agent = Agent()
    print(f"\nSORU: {question}")

    next_prompt = question # <--- DÜZELTME: Başlangıç değeri atandı

    # Maksimum 5 tur döngü
    for _ in range(5):
        result = agent.execute(question) if _ == 0 else agent.execute(next_prompt)
        print(f"\033[94m{result}\033[0m")

        actions = [action_re.match(a) for a in result.split('\n') if action_re.match(a)]
        if actions:
            action, val = actions[0].groups()
            if action in known_actions:
                print(f"=> Çalışıyor: {action} ({val.strip()})")
                obs = known_actions[action](val.strip())
                print(f"Gözlem: {str(obs)[:300]}...")
                next_prompt = f"Observation: {obs}\nThought:"
            else:
                break
        elif "Answer:" in result:
            print(f"\n✅ SONUÇ: {result.split('Answer:')[-1].strip()}")
            break

# TEST
if __name__ == "__main__":
    query("Anlaşmalı boşanma davası açmak için evlilik en az ne kadar sürmüş olmalıdır?")

# --- GENEL HUKUK BENCHMARK TESTİ (HUKUKV4 DATASETİNE UYGUN) ---

general_law_benchmark = [
    # --- KATEGORİ 1: Temel Hukuk Bilgisi (Anayasa & Medeni Hukuk) ---
    "Olağanüstü hal (OHAL) ilan etme yetkisi kime aittir?",
    "Milletvekili seçilme yaşı en az kaçtır?",
    "Cumhurbaşkanının görev süresi kaç yıldır ve bir kişi en fazla kaç kez seçilebilir?",
    "Anayasa Mahkemesi kaç üyeden oluşur?",
    "Evlenme ehliyeti kazanmak için olağan evlenme yaşı kaçtır?",
    "Ayırt etme gücüne sahip olmayan bir kişinin yaptığı evlilik geçerli midir?",
    "Anlaşmalı boşanma davası açabilmek için evlilik en az ne kadar sürmüş olmalıdır?",
    "Vasiyetname düzenleyebilmek için kişinin kaç yaşını doldurmuş olması gerekir?",
    "Mirasbırakanın altsoyu (çocukları) varken eşin yasal miras payı oranı nedir?",
    "Boşanma davası açıldıktan sonra eşlerin sadakat yükümlülüğü devam eder mi?",
    "Edinilmiş mallara katılma rejimine göre, evlilik öncesi alınan mallar paylaşıma dahil edilir mi?",
    "Babalık davası, çocuğun doğumundan itibaren en geç ne kadar süre içinde açılmalıdır?",
    "İsim değiştirme davası hangi mahkemede açılır?",

    # --- KATEGORİ 2: Ceza Hukuku & Borçlar Hukuku (Suç, Ceza ve Sözleşmeler) ---
    "Kasten öldürme suçunun temel şeklinin cezası nedir?",
    "Meşru müdafaa sınırının heyecan, korku veya telaş nedeniyle aşılması durumunda ceza verilir mi?",
    "Hırsızlık suçunun gece vakti işlenmesi cezayı nasıl etkiler?",
    "Hakaret suçunun ispat edilmesi durumunda ceza verilir mi?",
    "Taksirle bir kişinin ölümüne neden olmanın cezası nedir?",
    "Suça teşebbüs halinde cezada ne kadar indirim yapılır?",
    "Kiracı, kira sözleşmesini feshetmek isterse ev sahibine en az kaç gün önceden bildirmelidir?",
    "Sebepsiz zenginleşme davası açma süresi, mağdurun hakkını öğrendiği tarihten itibaren kaç yıldır?",
    "Kefalet sözleşmesinin geçerli olması için eşin rızası gerekli midir?",
    "Zamanaşımına uğramış bir borç, borçlu tarafından ödenirse geri istenebilir mi?",
    "Satılan malın ayıplı çıkması durumunda tüketicinin seçimlik hakları nelerdir?",
    "Borçlar Kanunu'na göre genel zamanaşımı süresi kaç yıldır?",

    # --- KATEGORİ 3: Matematiksel Hesaplamalar (Miras, Ceza İndirimi, Tazminat) ---
    "Mirasbırakanın eşi ve 3 çocuğu varsa, mirasın ne kadarı eşe kalır (Kesirli ifade)?",
    "Mirasbırakanın hiç çocuğu yoksa, eşi ve anne-babası hayatta ise eşin miras payı nedir?",
    "Müebbet hapis cezası alan bir hükümlü, koşullu salıverilmeden yararlanmak için en az kaç yıl cezaevinde kalmalıdır?",
    "Ağırlaştırılmış müebbet hapis cezası alan bir hükümlü kaç yıl yattıktan sonra koşullu salıverilebilir?",
    "Bir işçi 10.000 TL brüt ücret alıyorsa ve kıdem tazminatı tavanı 35.000 TL ise, 5 yıllık kıdemi için ne kadar tazminat alır?",
    "Gece vakti işlenen bir suçta ceza yarı oranında artırılıyorsa, 4 yıl hapis cezası alan biri toplam kaç yıl ceza alır?",
    "Yasal faiz oranı yıllık %9 ise, 100.000 TL'lik bir borcun 1 yıllık faizi kaç TL olur?",
    "Haftalık 45 saati aşan 4 saatlik fazla çalışma için, saatlik ücreti 200 TL olan işçiye ne kadar ödeme yapılır?",

    # --- KATEGORİ 4: Mantıksal Muhakeme ve Senaryo Analizi ---
    "Kiracı kirayı ödemezse ev sahibi hemen tahliye davası açabilir mi, yoksa önce ihtar mı çekmelidir?",
    "Bir kişi sarhoşken suç işlerse cezai ehliyeti tam mıdır yoksa ceza indirimi alır mı?",
    "Sözlü olarak yapılan gayrimenkul satış sözleşmesi geçerli midir?",
    "İşveren, işçiyi sendikaya üye olduğu için işten çıkarırsa bu geçerli bir fesih nedeni sayılır mı?",
    "Mirasçılar mirası reddetmek isterse (reddi miras), ölüm tarihinden itibaren kaç ay içinde başvuru yapmalıdır?",
    "Trafik kazasında yaralanan kişi, maddi ve manevi tazminat davasını kime karşı açabilir?"
]

print(f"Toplam {len(general_law_benchmark)} adet GENEL HUKUK sorusu teste tabi tutuluyor...\n")

# Ajanı her bir soru için çalıştır
for i, soru in enumerate(general_law_benchmark):
    print("\n" + "#"*60)
    print(f"BENCHMARK SORU: {i+1} / {len(general_law_benchmark)}")
    print("#"*60)

    try:
        # Ajanı çalıştır (Mevcut query fonksiyonunu kullanıyoruz)
        query(soru)
    except Exception as e:
        print(f"HATA OLUŞTU: {e}")

    print("\n" + "-"*30 + " SIRADAKİ SORU " + "-"*30 + "\n")

print("TÜM TESTLER BAŞARIYLA TAMAMLANDI.")