# -*- coding: utf-8 -*-
"""ik_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD6SmAzFSEOYc66lIxnJomHb2Ed2HRyE
"""

!pip install groq

import re
import math
from collections import Counter
from google.colab import userdata
from groq import Groq

# ======================================================
# 1. API KURULUMU (GROQ)
# ======================================================
# Colab'in solundaki 'Secrets' (Anahtar ikonu) kısmına
# GROQ_API_KEY adıyla anahtarını eklemeyi unutma.
try:
    groq_api_key = userdata.get('GROQ_API_KEY')
    client = Groq(api_key=groq_api_key)
except Exception as e:
    print("UYARI: GROQ_API_KEY bulunamadı. Lütfen Colab Secrets kısmına ekleyin.")

# ======================================================
# 2. RAG MOTORU (Senin Kodundaki SimpleRAG Sınıfı)
# ======================================================
class SimpleRAG:
    def __init__(self):
        self.vector_store = []

    def get_embedding(self, text):
        # Basit kelime sayma (Bag of Words) vektörü
        words = re.findall(r'\w+', text.lower())
        return Counter(words)

    def _cosine_similarity(self, vec1, vec2):
        intersection = set(vec1.keys()) & set(vec2.keys())
        numerator = sum([vec1[x] * vec2[x] for x in intersection])
        sum1 = sum([vec1[x]**2 for x in vec1.keys()])
        sum2 = sum([vec2[x]**2 for x in vec2.keys()])
        denominator = math.sqrt(sum1) * math.sqrt(sum2)
        return float(numerator) / denominator if denominator else 0.0

    def ingest(self, text):
        # Metni cümle/paragraf bazlı bölme
        chunks = [s.strip() for s in text.split('\n') if s.strip()]
        for chunk in chunks:
            self.vector_store.append({
                "content": chunk,
                "vector": self.get_embedding(chunk)
            })

    def retrieve(self, query, top_k=3):
        query_vec = self.get_embedding(query)
        scores = []
        for item in self.vector_store:
            score = self._cosine_similarity(query_vec, item["vector"])
            scores.append((score, item["content"]))
        scores.sort(key=lambda x: x[0], reverse=True)
        # Sadece alakalı sonuçları döndür
        return "\n".join([item[1] for item in scores[:top_k] if item[0] > 0.1])

# --- VERİ SETİNİ YÜKLÜYORUZ (DATASET) ---
rag_engine = SimpleRAG()

def load_data_from_json():
    with open('sirket_politikalari.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    # Başlık ve içeriği birleştirip tek metin haline getiriyoruz
    full_text = "\n\n".join([f"{item['baslik']}:\n{item['icerik']}" for item in data])
    return full_text

# Veriyi yükle ve RAG motoruna ver
dataset_text = load_data_from_json()
rag_engine = SimpleRAG()
rag_engine.ingest(dataset_text)

rag_engine.ingest(hr_policy_text)

# ======================================================
# 3. ARAÇLAR (TOOLS)
# ======================================================

def calculator(expression: str) -> str:
    """
    Matematiksel işlemleri yapar. Örn: 14 + 5 veya 300 * 20
    """
    try:
        # Güvenlik için sadece belirli karakterlere izin ver
        allowed_chars = set("0123456789+-*/(). ")
        if not all(c in allowed_chars for c in expression):
            return "Hata: Geçersiz karakter."
        return str(eval(expression))
    except Exception as e:
        return f"Hata: {e}"

def hr_policy_search(query: str) -> str:
    """
    Şirket politikaları, izinler, maaş ve kurallar hakkında bilgi arar.
    Örn: hr_policy_search: evlilik izni kaç gün
    """
    print(f"\n🔍 [RAG MODÜLÜ] Veritabanı taranıyor: '{query}'")
    result = rag_engine.retrieve(query)
    if not result:
        return "Politika dökümanlarında bu konuda bilgi bulunamadı."
    return f"Döküman Sonuçları:\n{result}"

# Araç Listesi
tools = [calculator, hr_policy_search]
tools_with_desc = "\n\n".join([tool.__name__ + tool.__doc__ for tool in tools])
known_actions = dict([(tool.__name__, tool) for tool in tools])

# ======================================================
# 4. AGENT VE PROMPT (BEYİN)
# ======================================================

system_prompt = f"""
Sen şirketin İnsan Kaynakları (İK) asistanısın.
Düşün (Thought), Aksiyon (Action), Dur (PAUSE) ve Gözlem (Observation) döngüsüyle çalışırsın.

KURALLAR:
1. Şirket kuralları, izinler ve maaşlar için MUTLAKA 'hr_policy_search' aracını kullan. Ezbere cevap verme.
2. Sayısal hesaplamalar (maaş toplamı, gün sayısı vb.) için 'calculator' kullan.
3. Her zaman Türkçe düşün ve Türkçe cevap ver.

Kullanabileceğin Araçlar:
{tools_with_desc}

Örnek Akış:
Soru: Evlenirsem kaç gün iznim olur ve bu yıllık izinden düşer mi?
Thought: Evlilik izni kuralını öğrenmek için politika araması yapmalıyım.
Action: hr_policy_search: evlilik izni
PAUSE
Observation: Evlenen çalışana 3 gün ücretli izin verilir, yıllık izinden düşülmez.
Answer: Evlilik durumunda 3 gün ücretli izniniz olur ve bu süre yıllık izninizden düşülmez.
""".strip()

class Agent:
    def __init__(self, system=""):
        self.system = system
        self.messages = []
        if self.system:
            self.messages.append({"role": "system", "content": system})

    def __call__(self, message):
        self.messages.append({"role": "user", "content": message})
        result = self.execute()
        self.messages.append({"role": "assistant", "content": result})
        return result

    def execute(self):
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile", # Groq üzerindeki güçlü model
            messages=self.messages,
            temperature=0,
            stop=["PAUSE", "Observation:", "<|"]
        )
        return completion.choices[0].message.content

# ======================================================
# 5. ÇALIŞTIRMA DÖNGÜSÜ (MAIN LOOP)
# ======================================================

action_re = re.compile(r'^Action: (\w+): (.*)$')

def query(question, max_turns=5):
    i = 0
    bot = Agent(system_prompt)
    next_prompt = question
    print(f"\n{'='*40}\nSORU: {question}\n{'='*40}")

    while i < max_turns:
        i += 1
        result = bot(next_prompt)
        print(f"\033[94m{result}\033[0m") # Mavi renkli çıktı

        # Action var mı kontrol et
        actions = [action_re.match(a) for a in result.split('\n') if action_re.match(a)]

        if actions:
            action, action_input = actions[0].groups()
            if action not in known_actions:
                print(f"Hata: Bilinmeyen aksiyon -> {action}")
                return

            print(f"=> Çalıştırılıyor: {action} ({action_input})")

            # Tool'u çalıştır
            observation = known_actions[action](action_input)
            print(f"Observation: {observation}")

            # Sonucu ajana geri besle
            next_prompt = f"Observation: {observation}"
        else:
            # Action yoksa cevap bitmiştir
            return

# ======================================================
# 6. GELİŞMİŞ TEST SENARYOLARI (BENCHMARK)
# ======================================================

print("\n--- SENARYO 1: TEMEL RAG (RETRIEVAL) ---")
# Amaç: Basit bilgi çekme yeteneğini gösterir[cite: 31].
query("Cuma günü ofise şortla gelebilir miyim?")


print("\n--- SENARYO 2: KARMAŞIK MATEMATİK (MATH + LOGIC) ---")
# Amaç: Ajanın formülü bulup (Maaş/12 * Katsayı) hesaplama yapmasını test eder[cite: 34, 35].
# Veri Setindeki Bilgi: Notu 5 olanın katsayısı 2.5'tir.
query("Yıllık brüt maaşım 600.000 TL ve performans notum 5 (Mükemmel). Yıl sonu primim tam olarak ne kadar yatar?")


print("\n--- SENARYO 3: ÇOKLU PARA BİRİMİ VE TOPLAMA (MULTI-HOP) ---")
# Amaç: Farklı maddelerdeki (Avrupa ve Asya) harcırahları bulup toplamasını test eder[cite: 34].
# Veri Setindeki Bilgi: Avrupa 130 Euro, Asya 110 USD.
query("Gelecek ay iş için 3 gün Paris'e (Avrupa), sonra 2 gün Tokyo'ya (Asya) gideceğim. Toplam harcırahım ne kadar tutar?")


print("\n--- SENARYO 4: KOŞULLU MANTIK VE İSTİSNA (EDGE CASE) ---")
# Amaç: Kuralın istisnasını (Deneme süresi) yakalayıp yakalamadığını test eder[cite: 5].
# Veri Setindeki Bilgi: İlk 2 ay (deneme süresi) uzaktan çalışma yasaktır.
query("İşe dün başladım (henüz 1. ayımdayım), haftada 3 gün evden çalışabilir miyim?")


print("\n--- SENARYO 5: ETİK VE SINIR DEĞER TESTİ (POLICY CHECK) ---")
# Amaç: Sayısal sınır kontrolü (50 USD) testi.
query("Bir tedarikçi bana 100 Dolar değerinde bir hediye gönderdi, bunu kabul etmemde sakınca var mı?")

import json

# ==========================================
# PROFESYONEL VE KAPSAMLI İK VERİ SETİ (V2 - GENİŞLETİLMİŞ)
# ==========================================

dataset = [
    # --- 1. MESAİ VE ÇALIŞMA DÜZENİ ---
    {
        "baslik": "Standart Çalışma Saatleri",
        "icerik": "Şirket genelinde mesai saatleri 08:30 - 17:30 arasındadır. Öğle molası 12:00-13:30 arasında 1.5 saattir. Cuma günleri 'Happy Hour' uygulaması nedeniyle mesai 16:00'da sona erer."
    },
    {
        "baslik": "Fazla Mesai (Overtime) Ücretleri",
        "icerik": "Haftalık 45 saati aşan çalışmalar fazla mesai sayılır. Hafta içi yapılan fazla mesailer saatlik ücretin 1.5 katı, hafta sonu ve resmi tatillerde yapılan çalışmalar ise saatlik ücretin 2.0 katı olarak ödenir. Yöneticiler (Manager ve üstü) fazla mesai ücreti almaz."
    },
    {
        "baslik": "Uzaktan Çalışma (Remote) Kuralları",
        "icerik": "Tam zamanlı çalışanlar haftada en fazla 3 gün evden çalışabilir. Ancak Pazartesi ve Perşembe günleri tüm ekiplerin ofiste olması zorunludur. Deneme süresindeki (ilk 2 ay) personelin uzaktan çalışma hakkı yoktur."
    },
    {
        "baslik": "Stajyer Çalışma Düzeni",
        "icerik": "Stajyerler haftada en az 3 gün ofise gelmek zorundadır. Stajyerlerin uzaktan çalışma (remote) hakkı bulunmamaktadır. Stajyer mesaisi 09:00-18:00 arasındadır."
    },
    {
        "baslik": "Gece Vardiyası Tazminatı",
        "icerik": "Akşam 20:00 ile sabah 06:00 arasındaki çalışmalar 'Gece Çalışması' kabul edilir. Bu saatlerde çalışan personele %30 ek vardiya tazminatı ödenir ve şirket tarafından eve dönüş taksi ücreti (Uber/BiTaksi fişi ile) karşılanır."
    },

    # --- 2. MAAŞ, PRİM VE FİNANSAL HAKLAR ---
    {
        "baslik": "Maaş Ödeme ve Avans",
        "icerik": "Maaşlar her ayın 1'inde ilgili banka hesabına yatar. Ayın 1'i tatile gelirse takip eden ilk iş günü ödeme yapılır. Ayın 15'inde maaşın %30'una kadar avans talep edilebilir."
    },
    {
        "baslik": "Yıl Sonu Performans Primi",
        "icerik": "Yıllık prim hesaplaması şöyledir: (Yıllık Brüt Maaş / 12) * (Performans Katsayısı). Katsayılar: Performans notu 5 (Mükemmel) için 2.5 maaş, 4 (İyi) için 1.5 maaş, 3 (Orta) için 0.5 maaş. Notu 3'ün altında olanlara prim ödenmez."
    },
    {
        "baslik": "Hisse Senedi Opsiyonları (ESOP)",
        "icerik": "Senior ve üzeri çalışanlara şirket hisse opsiyonu verilir. Hak ediş (Vesting) süresi 4 yıldır. İlk yılın sonunda %25'i hak edilir (Cliff), kalan %75 sonraki 3 yılda aylık eşit taksitlerle hak edilir."
    },
    {
        "baslik": "Yabancı Dil Tazminatı",
        "icerik": "İngilizce seviyesini belgeleyen (TOEFL 90+ veya IELTS 7.0+) personele aylık net 4.000 TL, Almanca veya Fransızca için (B2+) aylık net 3.000 TL dil tazminatı ödenir. Tazminat en fazla 2 dil için geçerlidir."
    },
    {
        "baslik": "Kıdem Teşvik Bonusu",
        "icerik": "Şirkette 5. yılını dolduranlara tek seferlik 50.000 TL, 10. yılını dolduranlara ise tek seferlik 100.000 TL sadakat bonusu ödenir."
    },

    # --- 3. YEMEK, YOL VE YAN HAKLAR ---
    {
        "baslik": "Yemek Kartı Uygulaması",
        "icerik": "Günlük yemek ücreti net 380 TL'dir. Bu tutar ay başında Sodexo veya Ticket kartına, o ayki iş günü sayısı kadar yüklenir. Raporlu veya izinli olunan günler için yemek ücreti yatırılmaz."
    },
    {
        "baslik": "Yol Yardımı ve Servis",
        "icerik": "Şirket servisini kullanmayan personele ikamet mesafesine göre yol yardımı yapılır. 0-15 km arası: Aylık 1.500 TL. 15-30 km arası: Aylık 2.500 TL. 30 km üzeri: Aylık 3.500 TL net ödeme yapılır."
    },
    {
        "baslik": "Özel Sağlık Sigortası (ÖSS)",
        "icerik": "Tüm çalışanlara 'Standart Yatarak Tedavi' sigortası yapılır. İsteyen çalışan maaşından aylık 1.200 TL kesinti yapılarak 'Kapsamlı Ayakta + Yatarak' paketine geçebilir. Eş ve çocuk ekletmek kişi başı aylık 800 TL'dir."
    },
    {
        "baslik": "İnternet ve Fatura Desteği",
        "icerik": "Uzaktan çalışma modeline dahil olan personele aylık 750 TL iletişim ve internet faturası desteği bordroya yansıtılarak ödenir."
    },
    {
        "baslik": "Kreş ve Çocuk Yardımı",
        "icerik": "0-6 yaş arası çocuğu olan kadın çalışanlara ve eşi çalışmayan erkek çalışanlara, çocuk başına aylık net 3.000 TL kreş yardımı ödenir. Bu yardım en fazla 2 çocuk için geçerlidir."
    },
    {
        "baslik": "Spor ve İyi Yaşam Desteği",
        "icerik": "Spor salonu üyeliği faturasını ibraz eden çalışanlara aylık 600 TL'ye kadar 'Wellbeing' ödemesi yapılır. Sigara kullanmayan personele yılda bir kez 2.000 TL 'Sağlıklı Yaşam Bonusu' verilir."
    },

    # --- 4. İZİNLER VE TATİLLER ---
    {
        "baslik": "Yıllık İzin Süreleri",
        "icerik": "Kıdemi 1-5 yıl olanlar: 14 iş günü. Kıdemi 5-15 yıl olanlar: 20 iş günü. Kıdemi 15 yıldan fazla olanlar: 26 iş günü. 50 yaş üstü çalışanlar kıdemi ne olursa olsun en az 20 gün izin hakkına sahiptir."
    },
    {
        "baslik": "Mazeret İzinleri",
        "icerik": "Evlilik İzni: 3 gün. Babalık İzni: 5 gün. Ölüm İzni (1. derece yakın): 3 gün. Taşınma İzni: Yılda 1 gün. Regl İzni: Kadın çalışanlar ayda 1 gün ücretli izin kullanabilir."
    },
    {
        "baslik": "Doğum Günü İzni",
        "icerik": "Çalışanlar, doğum günlerinin olduğu hafta içerisinde diledikleri 1 gün ücretli izin kullanabilirler."
    },
    {
        "baslik": "Sabbatical (Uzun Süreli Ayrılık)",
        "icerik": "Şirkette kesintisiz 7 yıl çalışan personel, kariyer molası (Sabbatical) hakkı kazanır. Bu kapsamda 3 ay boyunca maaşının %50'sini alarak ücretli izin yapabilir."
    },

    # --- 5. İŞ SEYAHATİ VE HARCIRAH ---
    {
        "baslik": "Yurt İçi Harcırah",
        "icerik": "Şehir dışı görevlendirmelerde konaklama ve ulaşım şirkete aittir. Ek olarak çalışana günlük 1.000 TL net cep harçlığı (harcırah) verilir."
    },
    {
        "baslik": "Yurt Dışı Harcırah (Döviz)",
        "icerik": "Yurt dışı görevlerde günlük harcırah bölgeye göre değişir. Avrupa Birliği ülkeleri: Günlük 130 Euro. Amerika ve Kanada: Günlük 160 USD. Orta Doğu ve Asya: Günlük 110 USD."
    },
    {
        "baslik": "Temsil ve Ağırlama Bütçesi",
        "icerik": "Müşteri yemeklerinde kişi başı harcama limiti 2.000 TL'dir. Alkol harcamaları şirket tarafından karşılanmaz. Ekip yemeklerinde kişi başı limit 1.200 TL'dir."
    },
    {
        "baslik": "Kendi Aracını Kullanma",
        "icerik": "Şirket işi için şahsi aracını kullanan personele km başına 12 TL yakıt desteği ödenir. Aylık maksimum 2.000 km ödeme yapılabilir."
    },

    # --- 6. İŞE ALIM VE REFERANS ---
    {
        "baslik": "Referans Bonusu Sistemi",
        "icerik": "Mevcut çalışanların önerdiği aday işe alınırsa bonus ödenir. Junior Pozisyon: 7.000 TL. Specialist/Mid Pozisyon: 15.000 TL. Senior/Lead Pozisyon: 25.000 TL. Yönetici/Manager: 40.000 TL. Ödeme, aday deneme süresini geçince yapılır."
    },
    {
        "baslik": "Taşınma (Relocation) Desteği",
        "icerik": "Şirket talebiyle başka bir şehre taşınan personele 1 maaş tutarında taşınma ikramiyesi ve nakliye masrafları (maksimum 30.000 TL) ödenir."
    },

    # --- 7. EĞİTİM VE CİHAZ ---
    {
        "baslik": "Eğitim Bütçesi ve Geri Ödeme",
        "icerik": "Her çalışanın yıllık 25.000 TL kişisel eğitim bütçesi vardır. Ancak, şirket tarafından karşılanan eğitimden sonra 6 ay içinde istifa eden çalışan, eğitim ücretinin tamamını (%100) geri öder."
    },
    {
        "baslik": "Cihaz Politikası ve BYOD",
        "icerik": "Çalışanlara MacBook Pro veya Dell XPS verilir. Kendi bilgisayarını kullanmak isteyen (BYOD) personele aylık 2.000 TL donanım kullanım bedeli ödenir."
    },

    # --- 8. ETİK VE GÜVENLİK ---
    {
        "baslik": "Hediye Kabul Politikası",
        "icerik": "Çalışanlar, tedarikçi veya müşterilerden piyasa değeri 50 USD (veya karşılığı TL) üzerindeki hediyeleri kabul edemez. Bu tutarın altındaki hediyeler İK'ya bildirilmelidir."
    },
    {
        "baslik": "Ek İş ve Çıkar Çatışması",
        "icerik": "Tam zamanlı çalışanların şirketten onay almadan başka bir işte (Freelance dahil) çalışması yasaktır. Rakip firmalarla iş yapmak kesinlikle yasaktır ve işten çıkarma sebebidir."
    },
    {
        "baslik": "Kıyafet ve Ofis Düzeni",
        "icerik": "Pazartesi-Perşembe arası 'Smart Casual' giyim zorunludur. Cuma günleri serbest kıyafettir ancak şort, terlik ve siyasi içerikli tişört yasaktır."
    },
    {
        "baslik": "Temiz Masa İlkesi",
        "icerik": "Mesai bitiminde masalarda gizli veya şirket içi (Internal) ibareli hiçbir döküman bırakılmamalıdır. İhlal durumunda ilk seferde uyarı, tekrarında disiplin cezası uygulanır."
    },

     # --- 9. İŞTEN AYRILMA ---
    {
        "baslik": "İhbar Süreleri",
        "icerik": "İstifa veya işten çıkarma durumunda ihbar süreleri şöyledir: 6 aya kadar çalışma için 2 hafta, 6 ay-1.5 yıl arası için 4 hafta, 1.5-3 yıl arası için 6 hafta, 3 yıldan fazla çalışma için 8 hafta."
    }
]

# Dosyayı JSON formatında kaydetme
with open('sirket_politikalari.json', 'w', encoding='utf-8') as f:
    json.dump(dataset, f, ensure_ascii=False, indent=4)

print(f"✅ DEV DATASET (V2) HAZIR: Toplam {len(dataset)} adet detaylı madde 'sirket_politikalari.json' dosyasına kaydedildi.")

# ======================================================
# DATASETİ YENİLEME VE RAG MOTORUNA YÜKLEME
# ======================================================

# 1. Mevcut motoru sıfırla
rag_engine = SimpleRAG()

# 2. Yeni JSON dosyasını oku
try:
    with open('sirket_politikalari.json', 'r', encoding='utf-8') as f:
        new_data = json.load(f)

    # 3. Veriyi metne çevirip birleştir
    # (Başlık ve İçeriği birleştiriyoruz ki ajan konuyu anlasın)
    full_text_data = "\n\n".join([f"POLİTİKA BAŞLIĞI: {item['baslik']}\nKURAL: {item['icerik']}" for item in new_data])

    # 4. RAG Motoruna yükle (Ingest)
    rag_engine.ingest(full_text_data)

    print(f"✅ BAŞARILI: {len(new_data)} adet yeni politika maddesi RAG motoruna yüklendi.")
    print("Artık test senaryolarını tekrar çalıştırabilirsin!")

except FileNotFoundError:
    print("HATA: 'sirket_politikalari.json' dosyası bulunamadı. Lütfen dataset oluşturma kodunu önce çalıştırın.")