# -*- coding: utf-8 -*-
"""is_hukuku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD6SmAzFSEOYc66lIxnJomHb2Ed2HRyE
"""

!pip install groq

import re
import math
from collections import Counter
from google.colab import userdata
from groq import Groq

!pip install PyPDF2
import os
import re
import math
import PyPDF2  # PDF okumak için
from collections import Counter

try:
    from groq import Groq
    from google.colab import userdata
    api_key = userdata.get('GROQ_API_KEY')
except:
    api_key = os.environ.get("GROQ_API_KEY")

client = Groq(api_key=api_key)

# --- 1. RAG MOTORU (SimpleRAG) ---
class SimpleRAG:
    def __init__(self):
        self.vector_store = []

    def get_embedding(self, text):
        words = re.findall(r'\w+', text.lower())
        return Counter(words)

    def _cosine_similarity(self, vec1, vec2):
        intersection = set(vec1.keys()) & set(vec2.keys())
        numerator = sum([vec1[x] * vec2[x] for x in intersection])
        sum1 = sum([vec1[x]**2 for x in vec1.keys()])
        sum2 = sum([vec2[x]**2 for x in vec2.keys()])
        denominator = math.sqrt(sum1) * math.sqrt(sum2)
        return float(numerator) / denominator if denominator else 0.0

    def ingest(self, text):
        # Metni "MADDE" kelimesine göre bölerek kanun maddelerini ayırıyoruz
        # Bu sayede her madde ayrı bir bilgi parçacığı (chunk) oluyor.
        chunks = text.split('MADDE')

        for chunk in chunks:
            if len(chunk.strip()) > 20: # Çok kısa parçaları atla
                # Başına tekrar MADDE ekle ki anlam bozulmasın
                clean_chunk = "MADDE " + chunk.strip()
                self.vector_store.append({"content": clean_chunk, "vector": self.get_embedding(clean_chunk)})

    def retrieve(self, query, top_k=3):
        query_vec = self.get_embedding(query)
        scores = sorted([(self._cosine_similarity(query_vec, item["vector"]), item["content"]) for item in self.vector_store], key=lambda x: x[0], reverse=True)
        return "\n---\n".join([item[1] for item in scores[:top_k] if item[0] > 0.05])

# --- 2. PDF OKUMA VE YÜKLEME ---
def load_pdf_data(pdf_path):
    full_text = ""
    try:
        with open(pdf_path, 'rb') as f:
            reader = PyPDF2.PdfReader(f)
            print(f"📄 PDF Yükleniyor... Toplam Sayfa: {len(reader.pages)}")
            for page in reader.pages:
                text = page.extract_text()
                if text:
                    full_text += text + "\n"
        return full_text
    except FileNotFoundError:
        return None

# Veri Setini Yükle (PDF'ten)
rag_engine = SimpleRAG()
pdf_content = load_pdf_data('document.pdf') # Senin yüklediğin dosya adı

if pdf_content:
    rag_engine.ingest(pdf_content)
    print("✅ İş Kanunu PDF'i başarıyla işlendi ve hafızaya alındı!")
else:
    print("⚠️ HATA: 'document.pdf' dosyası bulunamadı. Lütfen dosyayı yükleyin.")

# --- 3. ARAÇLAR (TOOLS) ---
def calculator(expression: str) -> str:
    """Matematiksel işlemleri yapar. Örn: 300 * 22 veya (600000/12)*1.5"""
    try:
        allowed = set("0123456789+-*/(). ")
        if not all(c in allowed for c in expression):
            return "Hata: Geçersiz karakter."
        return str(eval(expression, {"__builtins__": None}, {}))
    except Exception as e:
        return f"Hesaplama Hatası: {e}"

def kanun_ara(query: str) -> str:
    """İş kanunu maddeleri, izinler, tazminat ve haklar hakkında bilgi arar."""
    res = rag_engine.retrieve(query)
    return res if res else "Kanun maddelerinde bu konuda bilgi bulunamadı."

tools = [calculator, kanun_ara]
tools_desc = "\n".join([f"{t.__name__}: {t.__doc__}" for t in tools])
known_actions = {t.__name__: t for t in tools}

# --- 4. AJAN (AGENT) ---
system_prompt = f"""
Sen uzman bir Türk İş Hukuku Danışmanısın.
Kullanıcıların sorularını, yüklenen "4857 Sayılı İş Kanunu" PDF içeriğine dayanarak cevaplarsın.

KURALLAR:
1. Her cevabını mutlaka 'kanun_ara' aracıyla bulduğun KANUN MADDESİNE dayandır.
2. Hukuki hesaplamalar (Kıdem, İhbar, Fazla Mesai) için 'calculator' kullan.
3. Asla kişisel yorum yapma, sadece kanunda yazanı söyle.
4. Gerekli bilgiye ulaştığında veya cevap verebildiğinde 'Action: None' YAZMA. Bunun yerine direkt 'Answer:' etiketini kullan.

Araçlar:
{tools_desc}

Cevap Formatı (Sırayla):
Thought: (Düşünce süreci)
Action: tool_name: input (Eğer bilgiye ihtiyaç varsa)
Observation: (Aracın çıktısı)
... (Gerekirse tekrar Thought/Action/Observation) ...
Answer: (Sonuç cevabı - Sadece en sonda kullan)
"""

# --- 4. AGENT SINIFI (GÜNCELLENDİ: DAHA HAFİF MODEL) ---
class Agent:
    def __init__(self, system=""):
        self.system = system
        self.messages = []
        if self.system:
            self.messages.append({"role": "system", "content": system})

    def __call__(self, message):
        self.messages.append({"role": "user", "content": message})
        result = self.execute()
        self.messages.append({"role": "assistant", "content": result})
        return result

    def execute(self):
        # API çağrısı - MODELİ DEĞİŞTİRDİK
        # "llama-3.3-70b-versatile" YERİNE "llama-3.1-8b-instant" KULLANIYORUZ
        try:
            result = client.chat.completions.create(
                model="llama-3.1-8b-instant", # <-- DEĞİŞİKLİK BURADA
                messages=self.messages,
                temperature=0,
                stop=["PAUSE", "Observation:", "<|"]
            )
            return result.choices[0].message.content
        except Exception as e:
            return f"API HATASI: {e}"


# --- 5. ORKESTRASYON DÖNGÜSÜ (DÜZELTİLMİŞ) ---
import re
action_re = re.compile(r'^Action: (\w+): (.*)$')

def query(question, max_turns=10):
    i = 0
    # Agent sınıfı artık yukarıda tanımlı olduğu için hata vermeyecek
    react_agent = Agent(system_prompt)
    next_prompt = question

    print(f"\n{'='*40}\nQUESTION: {question}\n{'='*40}")

    while i < max_turns:
        i += 1
        result = react_agent(next_prompt)
        print(f"\033[94m{result}\033[0m") # Mavi renkli çıktı

        # Action satırlarını bul
        # Regex ile satır satır kontrol ediyoruz
        actions = [action_re.match(a) for a in result.split('\n') if action_re.match(a)]

        if actions:
            action, action_input = actions[0].groups()

            # Action adını ve inputu temizle (fazla boşlukları at)
            action = action.strip()
            action_input = action_input.strip()

            if action not in known_actions:
                print(f"Hata: Bilinmeyen aksiyon -> {action}")
                return

            print(f"=> Running {action} with input: {action_input}")

            try:
                # Fonksiyonu çalıştır
                observation = known_actions[action](action_input)
            except Exception as e:
                observation = f"Error executing tool: {e}"

            # --- DÜZELTME 1: Çıktı çok uzunsa kırpıyoruz ---
            observation_str = str(observation)
            if len(observation_str) > 2000:
                observation_str = observation_str[:2000] + "... (kısaltıldı)"

            print(f"Observation: {observation_str}")

            # --- DÜZELTME 2: Modele 'Düşünmeye Devam Et' komutu ---
            next_prompt = f"Observation: {observation_str}\nThought:"

        else:
            # Action yoksa cevap gelmiş demektir
            if "Answer:" in result:
                 print("\n\033[92m--- FINAL ANSWER FOUND ---\033[0m")
                 print(result.split("Answer:")[-1].strip())
            return

# Kodu çalıştırmak için (Önceki hücrelerde client, system_prompt ve tools tanımlı olmalı)
if __name__ == "__main__":
    query("Haftalık çalışma saati en fazla kaç olabilir?")

# --- 6. OTOMATİK BENCHMARK TESTİ ---

# Önce soruları listeye alıyoruz
benchmark_questions = [
    # --- KATEGORİ 1: Temel Bilgi ---
    "Deneme süresi en fazla kaç ay olabilir?",
    "Haftalık çalışma süresi yasal olarak en çok kaç saattir?",
    "Yıllık ücretli izin hakkı kazanmak için en az ne kadar çalışmak gerekir?",
    "Gece çalışma süresi en fazla kaç saat olabilir?",
    "Ara dinlenmesi 4 saatten kısa süreli işlerde kaç dakikadır?",
    "7.5 saatten fazla süren işlerde ara dinlenmesi ne kadardır?",
    "Erkek işçiye eşinin doğum yapması halinde kaç gün izin verilir?",
    "İşçinin evlenmesi durumunda kaç gün mazeret izni verilir?",
    "Birinci derece yakınını kaybeden işçiye kaç gün ölüm izni verilir?",
    "Süt izni, çocuk kaç yaşına gelene kadar kullandırılır?",
    "Günde 1.5 saat olan süt izni hangi yaş grubundaki çocuklar içindir?",
    "İş sözleşmesi feshinde bildirim süresi 6 aydan az çalışan işçi için kaç haftadır?",
    "6 ay ile 1.5 yıl arası kıdemi olan işçi için ihbar süresi kaç haftadır?",
    "1.5 yıl ile 3 yıl arası kıdemi olan işçi için ihbar süresi kaç haftadır?",
    "3 yıldan fazla kıdemi olan işçi için ihbar süresi kaç haftadır?",
    "Yeni iş arama izni günde en az kaç saattir?",
    "Kadın işçiler doğumdan önce kaç hafta çalıştırılmaz?",
    "Kadın işçiler doğumdan sonra kaç hafta çalıştırılmaz?",
    "Zorunlu nedenlerle fazla çalışma durumunda işçinin onayı gerekir mi?",
    "Telafi çalışması günde en fazla kaç saat olabilir?",
    "Telafi çalışması tatil günlerinde yapılabilir mi?",
    "Ücret kesme cezası bir ayda en fazla ne kadar olabilir?",
    "Kısmi süreli çalışan işçinin sigorta prim gün sayısı nasıl hesaplanır?",
    "Çağrı üzerine çalışmada haftalık çalışma süresi belirlenmemişse kaç saat kabul edilir?",
    "Yeraltı ve maden işlerinde çalışanların yıllık izin süreleri kaç gün artırılır?",

    # --- KATEGORİ 2: Hesaplama ve Mantık ---
    "Haftalık 45 saati aşan her bir saat fazla çalışma için ücret yüzde kaç zamlı ödenir?",
    "İşçi fazla çalışma ücreti yerine serbest zaman kullanmak isterse, 1 saatlik fazla çalışma için kaç dakika serbest zaman hak eder?",
    "Fazla sürelerle çalışmalarda (45 saatin altında anlaşılan durumlarda) her bir saat için ücret yüzde kaç artırılır?",
    "5 yıllık kıdemi olan bir işçinin yıllık izin süresi kaç gündür?",
    "16 yaşındaki bir işçinin yıllık ücretli izin süresi en az kaç gün olabilir?",
    "55 yaşındaki bir işçinin yıllık ücretli izin süresi en az kaç gün olabilir?",
    "Kıdem tazminatı hesaplanırken bir işçinin 5 yıl 6 ay çalışması varsa, 6 aylık kısım hesaba katılır mı?",
    "Bir işçi günde 11 saatten fazla çalıştırılabilir mi?",
    "İşçinin brüt ücreti 20.000 TL ise ve 10 saat fazla mesai yaptıysa, fazla mesai ücreti toplamı ne kadar olur?",
    "İşçi haklı nedenle derhal fesih yaparsa ihbar tazminatı öder mi?",
    "İşveren haklı nedenle (Madde 25/II) fesih yaparsa kıdem tazminatı öder mi?",
    "İhbar süresine uyulmadan işten çıkarılan 4 yıllık bir işçiye ne kadarlık ücret tutarında ihbar tazminatı ödenmelidir?",
    "Bir yılda yapılabilecek toplam fazla çalışma süresi en çok kaç saattir?",
    "Haftalık iş günlerinin 6 gün olduğu bir işyerinde, günde 7.5 saat çalışan işçi haftada kaç saat çalışmış olur?",
    "Engelli personel çalıştırma zorunluluğu oranı yüzde kaçtır?",

    # --- KATEGORİ 3: Zor Sorular ---
    "Belirli süreli iş sözleşmesi kendiliğinden sona erdiğinde kıdem tazminatı ödenir mi?",
    "Hamilelik nedeniyle işten ayrılan işçi kıdem tazminatı alabilir mi?",
    "Askerlik nedeniyle işten ayrılan işçi kıdem tazminatı alabilir mi?",
    "İşçi kendi isteğiyle (istifa) ayrılırsa kıdem tazminatı alabilir mi?",
    "Hafta tatilinde çalışan işçiye ücreti nasıl ödenir?"
]

print(f"Toplam {len(benchmark_questions)} adet soru teste tabi tutuluyor...\n")

# Döngüyü başlatıyoruz ve her soruyu ajana soruyoruz
for i, soru in enumerate(benchmark_questions):
    print("\n" + "#"*60)
    print(f"TEST NO: {i+1} / {len(benchmark_questions)}")
    print("#"*60)

    try:
        # Senin query fonksiyonunu çağırıyoruz
        query(soru)
    except Exception as e:
        print(f"HATA: Bu soruda bir sorun oluştu: {e}")

    print("\n" + "-"*30 + " SONRAKİ SORUYA GEÇİLİYOR " + "-"*30 + "\n")

print("TÜM TESTLER TAMAMLANDI.")